### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by dinkel1975** [tobias-93/esphome-ecodan-heatpump#11]
Hi,

I don´t have a code for my ecodan!
where can I get it?

Best regards 
Michael

**Comment by tobias-93** [comment]
Hi Michael, I'm not sure what code you are referring to. As far as I know, my code runs perfectly fine on an ESP device hooked up to the CN105 connector of an Ecodan heatpump, no additional code required...

**Comment by dinkel1975** [comment]
hi,

i mean the encryption key from your instalation guide.

________________________________

**Comment by tobias-93** [comment]
Hi, the encryption key is generated by ESPHome (and used to encrypt the data sent from the ESP device towards Home Assistant and vice versa), so it is not related to the heatpump. If you follow step 2 from the guide you will end up with the key.

**Comment by dinkel1975** [comment]
thank you!

________________________________

**Comment by dinkel1975** [comment]
can i use a esp32 also? i have one at home. Do i have something to observe?

________________________________

**Comment by tobias-93** [comment]
That should also work, you just have to make sure you configure your UART in your device's YAML file. The configuration for an ESP8266 is here: https://github.com/tobias-93/esphome-ecodan-heatpump/blob/2fdf15ba675699c0c2ca8c1692a31505cb02cc8f/heatpump.yaml#L32, you can do something similar for an ESP32 but probably with a different TX/RX GPIO

**Comment by dinkel1975** [comment]
great. thank you

________________________________

**Comment by dinkel1975** [comment]
I have give it a try but I get following error when downloading your package

***@***.***

Von: Tobias Feijten ***@***.***>
Gesendet: Freitag, 22. März 2024 10:32
An: tobias-93/esphome-ecodan-heatpump ***@***.***>
Cc: dinkel1975 ***@***.***>; Author ***@***.***>
Betreff: Re: [tobias-93/esphome-ecodan-heatpump] Code (Issue #11)


That should also work, you just have to make sure you configure your UART in your device's YAML file. The configuration for an ESP8266 is here: https://github.com/tobias-93/esphome-ecodan-heatpump/blob/2fdf15ba675699c0c2ca8c1692a31505cb02cc8f/heatpump.yaml#L32, you can do something similar for an ESP32 but probably with a different TX/RX GPIO

-

**Comment by tobias-93** [comment]
I'm missing part of your message, can you try to reply on Github instead of replying to the e-mail?

**Comment by dinkel1975** [comment]
I have give it a try but I get following error when downloading your package
![error](https://github.com/tobias-93/esphome-ecodan-heatpump/assets/97777790/0abe4a24-074c-4d0e-8336-ca524765b6f8)

**Comment by tobias-93** [comment]
This is not related to the package I created, and since you're using a configuration which I didn't test I cannot help you unfortunately. You can try to Google this error, maybe someone else ran into this and has the solution...

**Comment by dinkel1975** [comment]
i think i will use a 8266

**Comment by dinkel1975** [comment]
i have found a esp8266. it works. thank you

![Screenshot 2024-03-22 172703](https://github.com/tobias-93/esphome-ecodan-heatpump/assets/97777790/8555d803-bba9-4999-a107-e4381902e21f)

**Comment by tobias-93** [comment]
That's nice to hear!

**Comment by dinkel1975** [comment]
what i not found is, how to switch operating mode (heat, cool,...)

**Comment by dinkel1975** [comment]
excuse me. i have found it. everying is OK! thank you very much for your help!

**Comment by dinkel1975** [comment]
Do you have an idea? I don´t get an serial connection. I have a ESRC-VM2B.

**Comment by dinkel1975** [comment]
I made it after all!
My 5V to 3.3V component for the RX and TX lines didn't work. Now I get values.

Now I would like to change the language of the "Selects". How can I do that?
